import random

def random_quote():
  return wateringaffirmation_list[random.randint(0, len(wateringaffirmation_list) - 1)]

nice_list = [
  "I love how you see the world.",
  "You broaden my perspective.",
  "You rocked that situation.",
  "Great job today!",
  "I love your smile.",
  "I love your laugh.",
  "I love your eyes.",
  "You’re so fun",
  "You’re so exciting",
  "You’re so hilarious.",
  "You’ve totally got this!",
  "Your perspective is invaluable.",
  "I have total confidence in you.",
  "You look amazing!",
  "You’re a dream come true.",
  "You’re one in a million.",
  "You’re so interesting.",
  "You look amazing!",
  "I just want to let you know how proud of you I am.",
  "You’re doing such a great job. I’m really proud of you.", 
  "Wow! You look so good! I really love the new outfit. It looks great on you!", 
  "I believe in you.",
  "You handled that like a pro.",
  "You’re one of my favorite people to be around.",
  "You’re an inspiration!",
  "Your being here makes everything better.",
  "You inspire me.",
  "You are amazing.",
  "You did that! Go you!",
  "I learn so much from you.",
  "I love your ideas.",
  "I see how hard you’ve been working on what you love",
  "I love how your mind works.",
  "I love how you see things.",
  "I love how funny you are.",
  "I am proud of you when you love yourself",
  "Being with you makes me so happy!",
  "Being with you makes me so inspired!",
  "Being with you makes me so joyful!",
  "You make so many things possible.",
  "Hello, gorgeous.",
  "Your opinion means so much to me.",
  "You have the best sense of humor.",
  "I’ll always be here for you.",
  "You make everything more fun.",

]
wateringaffirmation_list = [
  "You work really hard for us, and even when things may feel tough, I just want you to know how appreciative I am.",
  "I feel so lucky to have you.",
  "Thanks for that",
  "I appreciate you", 
  "I’m so lucky to be with you.",
  "You make my heart sing.",
  "You make everything better. Thank you!",
  "I couldn’t do this without you.",
  "I’m so glad you’re in my life.",
  "I know I can always count on you.",
  "You’re so fun to be with. Thanks for taking care of us!",
  "You’re so special to me. Thanks for taking care of us today!",
  "I feel so grateful that I get to be with you. Thank you!",
  "I love our life together, thanks!",
  "I’m so happy to see you. Have a great day",
  "You’re the best!",
  "You’re such a good partner.",
  "I’m so proud of you, thanks for taking care of us.",
  "Your support means the world to me.",
  "I hope you know how much you mean to me.",
  "Thank you for being honest with me.",
  "You’re so thoughtful, thanks.",
  "You’re so kind, thank you.",
  "My life is more meaningful with you in it.",
  "I love how well you understand me, I needed water.",
  "Thanks! You’re my best friend.",
  "You take such good care of me.",
  "You help me so much.",
  "Thank you for being in my life.",
  "We work so well together.",
  "I love you, thank you so much.",
  "You are my sunshine.",
  "I love that you did this for me.",
  "You are amazing. Thanks for that!",
  "Thank you for taking the time to do this with me.",
  "You did that! Go you!",
  "You do so much for the people in your life.",
  "I’m proud to be your partner.",
  "I love how you make time for me.",
  "I love being with you.",
  "You know how to make me laugh!",
  "You know how to make me happy!",
  "I feel safe with you.",
  "We make a great team.",
  "You’re so considerate.",
  "You really are the best.",
  "I love your company.",
  "Do you know how much I love you? Thanks for taking care of us today",
  "Things feel easier with you here.",
  "You help me in so many ways.",
  "I don’t know what I’d do without you.",
  "I feel so lucky to have you in my life.",
  "I appreciate you.",
  "Thank you for loving me.",
  "Being with you makes me so happy!",
  "Being with you makes me so inspired!",
  "Being with you makes me so joyful!",
  "Thank you for taking care of me.",
  "I love how you take the time to water me"
]